-- 1. Базовые таблицы
CREATE TABLE university.buildings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(255) NOT NULL,
    address TEXT NOT NULL
);

CREATE TABLE university.roles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE university.users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    password VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

-- 2. Связующие и простые таблицы
CREATE TABLE university.user_roles (
    role_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY(role_id, user_id),
    FOREIGN KEY(user_id) REFERENCES university.users(id) ON DELETE CASCADE,
    FOREIGN KEY(role_id) REFERENCES university.roles(id) ON DELETE CASCADE
);

CREATE TABLE university.employees (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL UNIQUE,
    position VARCHAR(255) NOT NULL,
    FOREIGN KEY(user_id) REFERENCES university.users(id) ON DELETE CASCADE
);

CREATE TABLE university.classrooms (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(255) NOT NULL,
    building_id INTEGER NOT NULL,
    room_number VARCHAR(20) NOT NULL,
    FOREIGN KEY(building_id) REFERENCES university.buildings(id) ON DELETE RESTRICT
);

-- 3. Академические таблицы
CREATE TABLE university.faculties (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE,
    building_id INTEGER NOT NULL,
    director_id INTEGER, -- Если директор временно отсутствует
    FOREIGN KEY(building_id) REFERENCES university.buildings(id) ON DELETE RESTRICT,
    FOREIGN KEY(director_id) REFERENCES university.employees(id) ON DELETE SET NULL
);

CREATE TABLE university.departments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    faculty_id INTEGER NOT NULL,
    FOREIGN KEY(faculty_id) REFERENCES university.faculties(id) ON DELETE CASCADE
);

CREATE TABLE university.specializations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    faculty_id INTEGER NOT NULL,
    description TEXT,
    FOREIGN KEY(faculty_id) REFERENCES university.faculties(id) ON DELETE CASCADE
);

CREATE TABLE university.groups (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    admission_year SMALLINT NOT NULL,
    specialization_id INTEGER NOT NULL,
    faculty_id INTEGER NOT NULL,
    FOREIGN KEY(faculty_id) REFERENCES university.faculties(id) ON DELETE CASCADE,
    FOREIGN KEY(specialization_id) REFERENCES university.specializations(id) ON DELETE RESTRICT
);

-- 4. Преподаватели и дисциплины
CREATE TABLE university.teachers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    academic_degree VARCHAR(100),
    department_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL UNIQUE,
    FOREIGN KEY(employee_id) REFERENCES university.employees(id) ON DELETE CASCADE,
    FOREIGN KEY(department_id) REFERENCES university.departments(id) ON DELETE RESTRICT
);

CREATE TABLE university.disciplines (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    department_id INTEGER NOT NULL,
    FOREIGN KEY(department_id) REFERENCES university.departments(id) ON DELETE RESTRICT
);

CREATE TABLE university.teacher_disciplines (
    teacher_id INTEGER NOT NULL,
    discipline_id INTEGER NOT NULL,
    PRIMARY KEY(teacher_id, discipline_id),
    FOREIGN KEY(teacher_id) REFERENCES university.teachers(id) ON DELETE CASCADE,
    FOREIGN KEY(discipline_id) REFERENCES university.disciplines(id) ON DELETE CASCADE
);

-- 5. Студенты и расписание
CREATE TABLE university.students (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id_number VARCHAR(50) UNIQUE,
    group_id INTEGER,
    user_id INTEGER NOT NULL UNIQUE,
    FOREIGN KEY(user_id) REFERENCES university.users(id) ON DELETE CASCADE,
    FOREIGN KEY(group_id) REFERENCES university.groups(id) ON DELETE SET NULL
);

CREATE TABLE university.lessons (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    teacher_id INTEGER NOT NULL,
    classroom_id INTEGER NOT NULL,
    discipline_id INTEGER NOT NULL,
    lesson_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    type VARCHAR(255) NOT NULL,
    FOREIGN KEY(classroom_id) REFERENCES university.classrooms(id) ON DELETE RESTRICT,
    FOREIGN KEY(teacher_id) REFERENCES university.teachers(id) ON DELETE RESTRICT,
    FOREIGN KEY(discipline_id) REFERENCES university.disciplines(id) ON DELETE RESTRICT
);

-- 6. Посещения 
CREATE TABLE university.attendances (
    student_id INTEGER NOT NULL,
    lesson_id INTEGER NOT NULL,
    status VARCHAR(20) DEFAULT 'present',
    recorded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(student_id, lesson_id),
    FOREIGN KEY(student_id) REFERENCES university.students(id) ON DELETE CASCADE,
    FOREIGN KEY(lesson_id) REFERENCES university.lessons(id) ON DELETE CASCADE
);

-- Оценки и успеваемость
CREATE TABLE university.grades (
    id SERIAL PRIMARY KEY,
    student_id INTEGER NOT NULL,
    discipline_id INTEGER NOT NULL,
    lesson_id INTEGER,
    grade_value DECIMAL(3,1) CHECK (grade_value IS NULL OR (grade_value >= 0 AND grade_value <= 100)),
    grade_type VARCHAR(50) NOT NULL CHECK (grade_type IN (
        'exam',
        'test',
        'homework',
        'participation'
    )), 
    semester VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id, discipline_id, lesson_id, grade_type),
    FOREIGN KEY(student_id) REFERENCES university.students(id) ON DELETE CASCADE,
    FOREIGN KEY(discipline_id) REFERENCES university.disciplines(id) ON DELETE RESTRICT,
    FOREIGN KEY(lesson_id) REFERENCES university.lessons(id) ON DELETE SET NULL
);

-- Учебные планы
CREATE TABLE university.curriculum (
    id SERIAL PRIMARY KEY,
    specialization_id INTEGER NOT NULL,
    discipline_id INTEGER NOT NULL,
    semester_number INTEGER NOT NULL CHECK (semester_number >= 1 AND semester_number <= 12),
    hours_total INTEGER NOT NULL,
    hours_lecture INTEGER,
    hours_practice INTEGER,
    is_required BOOLEAN DEFAULT true,
    FOREIGN KEY(specialization_id) REFERENCES university.specializations(id) ON DELETE CASCADE,
    FOREIGN KEY(discipline_id) REFERENCES university.disciplines(id) ON DELETE CASCADE,
    UNIQUE(specialization_id, discipline_id, semester_number)
);