-- 1. Базовые таблицы
CREATE TABLE "buildings" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "type" VARCHAR(255) NOT NULL,
    "address" TEXT NOT NULL
);

CREATE TABLE "roles" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT
);

CREATE TABLE "users" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "password" VARCHAR(255) NOT NULL,
    "login" VARCHAR(255) NOT NULL UNIQUE,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "name" VARCHAR(255) NOT NULL
);

-- 2. Связующие и простые таблицы
CREATE TABLE "user_roles" (
    "role_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    PRIMARY KEY("role_id", "user_id"),
    FOREIGN KEY("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    FOREIGN KEY("role_id") REFERENCES "roles"("id") ON DELETE CASCADE
);

CREATE TABLE "employees" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER NOT NULL UNIQUE,
    "position" VARCHAR(255) NOT NULL,
    FOREIGN KEY("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE "classrooms" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "type" VARCHAR(255) NOT NULL,
    "building_id" INTEGER NOT NULL,
    "room_number" VARCHAR(20) NOT NULL,
    FOREIGN KEY("building_id") REFERENCES "buildings"("id") ON DELETE RESTRICT
);

-- 3. Академические таблицы
CREATE TABLE "faculties" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL UNIQUE,
    "building_id" INTEGER NOT NULL,
    "director_id" INTEGER NOT NULL,
    FOREIGN KEY("building_id") REFERENCES "buildings"("id") ON DELETE RESTRICT,
    FOREIGN KEY("director_id") REFERENCES "employees"("id") ON DELETE RESTRICT
);

CREATE TABLE "departments" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    "faculty_id" INTEGER NOT NULL,  -- исправлено имя поля
    FOREIGN KEY("faculty_id") REFERENCES "faculties"("id") ON DELETE CASCADE  -- исправлено имя FK
);

CREATE TABLE "groups" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    "admission_year" SMALLINT NOT NULL,
    "specialization" VARCHAR(255) NOT NULL,
    "faculty_id" INTEGER NOT NULL,
    FOREIGN KEY("faculty_id") REFERENCES "faculties"("id") ON DELETE RESTRICT
);

-- 4. Преподаватели и дисциплины
CREATE TABLE "teachers" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "academic_degree" VARCHAR(100),
    "department_id" INTEGER NOT NULL,
    "employ_id" INTEGER NOT NULL UNIQUE,
    FOREIGN KEY("employ_id") REFERENCES "employees"("id") ON DELETE CASCADE,
    FOREIGN KEY("department_id") REFERENCES "departments"("id") ON DELETE RESTRICT
);

CREATE TABLE "disciplines" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL UNIQUE,
    "description" TEXT,
    "department_id" INTEGER NOT NULL,
    FOREIGN KEY("department_id") REFERENCES "departments"("id") ON DELETE RESTRICT
);

CREATE TABLE "teacher_discipline" (
    "teacher_id" INTEGER NOT NULL,
    "discipline_id" INTEGER NOT NULL,
    PRIMARY KEY("teacher_id", "discipline_id"),
    FOREIGN KEY("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE,
    FOREIGN KEY("discipline_id") REFERENCES "disciplines"("id") ON DELETE CASCADE
);

-- 5. Студенты и расписание
CREATE TABLE "students" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "student_id_number" VARCHAR(50) UNIQUE,
    "group_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL UNIQUE,
    FOREIGN KEY("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    FOREIGN KEY("group_id") REFERENCES "groups"("id") ON DELETE RESTRICT
);

CREATE TABLE "lessons" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "teacher_id" INTEGER NOT NULL,
    "classroom_id" INTEGER NOT NULL,
    "discipline_id" INTEGER NOT NULL,
    "lesson_date" DATE NOT NULL,
    "start_time" TIME NOT NULL,
    "end_time" TIME NOT NULL,
    "type" VARCHAR(255) NOT NULL,
    FOREIGN KEY("classroom_id") REFERENCES "classrooms"("id") ON DELETE RESTRICT,
    FOREIGN KEY("teacher_id") REFERENCES "teachers"("id") ON DELETE RESTRICT,
    FOREIGN KEY("discipline_id") REFERENCES "disciplines"("id") ON DELETE RESTRICT
);

-- 6. Посещения 
CREATE TABLE "attendances" (
    "student_id" INTEGER NOT NULL,
    "lesson_id" INTEGER NOT NULL,
    "status" VARCHAR(20) DEFAULT 'present',
    "recorded_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("student_id", "lesson_id"),
    FOREIGN KEY("student_id") REFERENCES "students"("id") ON DELETE CASCADE,
    FOREIGN KEY("lesson_id") REFERENCES "lessons"("id") ON DELETE CASCADE
);