events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # Подключаем конфиги сайтов
    include /etc/nginx/conf.d/*.conf;
}

# если сертификаты лягут , ввести в повершел: 
# Import-Certificate -FilePath "D:\my-personal-account\nginx\ssl\cert.pem" -CertStoreLocation Cert:\LocalMachine\Root