upstream dotnet {
    server dotnet:80;
}

server {
    listen 443 ssl;
    http2 on;
    server_name localhost;

    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    access_log /var/log/nginx/university_access.log main;
    error_log /var/log/nginx/university_error.log;

    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    location /api/lessons {
        proxy_pass http://dotnet;
        #
        proxy_set_header Host $host;
        #айпи адрес клиента
        proxy_set_header X-Real-IP $remote_addr;
        #собирает все в цепочки, когда например клиент через несколько прокси проходит
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #передает протокол который использовал клиент
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /dotnet/swagger/ {
        proxy_pass http://dotnet/swagger/;
        proxy_set_header Host $host;
    }

    location /api/weatherforecast {
        proxy_pass http://dotnet;
        proxy_set_header Host $host;
    }

    location / {
        return 200 "Tuk-tuk. Kto tam?\n";
        add_header Content-Type "text/plain charset=utf-8";
    }
}
